# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ${file(.credentials.yml):service.name}

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
  # you can define service wide environment variables here
  environment:
    # SHOPIFY_NAME: ${file(.credentials.yml):shopify.shopName}
    # SHOPIFY_APIKEY: ${file(.credentials.yml):shopify.apiKey}
    # SHOPIFY_PASSWORD: ${file(.credentials.yml):shopify.password}
# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  getContacts:
    handler: handler.getContacts
    events:
      - http: GET contacts
  login:
    handler: handler.login
    events:
      - http: POST api/oauth2/login
  getDoctors:
    handler: core/models/doctor.get
    events:
      - http: GET api/doctors
  createDoctor:
    handler: core/models/doctor.post
    events:
      - http: POST api/doctors
  updateDoctor:
    handler: core/models/doctor.put
    events:
      - http: PUT api/doctors/{id}
        request: 
          parameters: 
             paths: 
               id: true
  initDb:
    handler: setup.initDb
    events:
      - http: GET api/db/init
#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
resources:  
  Resources:
    DoctorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: doctors
        AttributeDefinitions:
          - AttributeName: doctor_id
            AttributeType: S
        KeySchema:
          - AttributeName: doctor_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DoctorTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: arn:aws:dynamodb:*:*:table/doctors
        Roles:
          - Ref: IamRoleLambdaExecution
